### PR TITLE
Fix ECONNRESET for Agent

### PR DESCRIPTION
**Pull request by mihai1voicescu**
https://github.com/molnarg/node-http2/issues/194

### CODE REVIEW

**Comment by felicienfrancois** [comment]
Calling emit after destroy seems strange. Does this work ? I through EventEmitters stop emitting events after destroy.
did you tested it?
on both nodejs <4.x and >4.x ?

**Comment by felicienfrancois** [comment]
If so, maybe this fix should be applied only when the error is ECONNRESET

```
if (err.code==='ECONNRESET') {
  // here
}
```

**Comment by mihai1voicescu** [comment]
I tested it after 4.x. This code segment is taken directly from the official Node.Js fix (https://github.com/nodejs/node/issues/3595). Also, in my opinion, a socket that has an error but no associated request should be closed.

**Comment by felicienfrancois** [comment]
OK, thank you

**Pull request merged**
